### ISSUE TITLE
Create Team Section in Navbar

### ISSUE THREAD

**Issue by sourav-biggboss** [olfant/.github#12]
We need to add a new "Team" section to the navbar and develop a detailed team webpage showcasing the various teams at Olfant. The tasks involved are:

Add "Team" Section to Navbar:

Update the website's navbar to include a "Team" section that links to the new team webpage.
Develop Comprehensive Team Web Page:

Create a new team webpage that includes the website's standard header and footer.
Ensure the UI design of the page is consistent with the overall website, maintaining the same patterns and aesthetics.
Design Team Sections:

The webpage will feature the following teams, each with a dedicated section:
Custom Software Development: Develop tailored software solutions to meet business needs and streamline operations.
Digital Marketing: Enhance online presence and reach target audiences with strategic digital marketing campaigns.
Graphic Design: Create visually appealing designs that elevate brand identity and engage audiences.
SEO Services: Optimize websites to rank higher in search engine results and attract more organic traffic.
IT Consultancy: Provide expert advice to improve IT infrastructure and implement effective technology solutions.
Cloud Solutions: Leverage cloud computing to enhance scalability, flexibility, and security.
Each section will feature a catalogue of team members displayed in cards, with pictures, designations, and brief descriptions.
Implement a slider or grid layout for displaying team members within each section.
UI Enhancement and R&D:

Improve the overall UI with research and development (R&D) efforts, ensuring the team section is visually appealing and user-friendly.
Maintain consistency with the website's UI pattern while enhancing the design for a modern look.
Examples and Best Practices:

Research online examples of effective team webpages for ideas and inspiration regarding layout, design, and functionality.

**Comment by Ajaywebsite** [comment]
#12 complete
