### ISSUE TITLE
Bug Report: Issues in Local Enquiry Form and Service Payment Flow

### ISSUE THREAD

**Issue by Ajaywebsite** [olfant/.github#23]
Module 1: Local Enquiry Form
Description:
The Local Enquiry Form is not submitting data, preventing users from completing their enquiries.

Steps to Reproduce:

Navigate to the [Local Enquiry Form](https://olfant.com/).
Fill in all the required fields.
Click on the "Submit" button.
Expected Result:
The form should submit successfully, and the entered data should be stored in the database.

Actual Result:
The form does not submit, and no confirmation or error message is displayed.

Module 2: Service Payment Flow
Description:
When selecting a service and proceeding to the payment section:

An Order ID is generated successfully.
The Payment ID fails to generate.
Payments via the Test Wallet do not succeed.
Issue 1: Payment ID Not Generated
Steps to Reproduce:

Navigate to the Services section.
Select any service and proceed to the payment section.
Attempt to make a payment.
Expected Result:
A unique Payment ID should be generated for every transaction.

Actual Result:
The Payment ID is not generated, blocking the payment process.

Issue 2: Test Wallet Payment Fails
Steps to Reproduce:

Follow the steps mentioned in Issue 1 to reach the payment section.
Choose the Test Wallet payment option and proceed to pay.
Expected Result:
The payment should succeed, and the user should receive a confirmation.

Actual Result:
The payment does not succeed, and no clear error message or confirmation is provided.

**Comment by GouravTheDeveloper7668** [comment]
@sourav-biggboss  Issue Closed !!
